- hosts: apache
  sudo: yes
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes state=latest
      with_items:
        - php
        - apache2
    - name: ensure php
      lineinfile: dest=/etc/php/7.2/apache2/php.ini regexp="^session.save_handler = files" line="session.save_handler = memcache"
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
    - name: Creates directory
      file:
      path: /applications/vendo-iac-test
      state: directory
      owner: www-data
      group: www-data
      mode: 0775
      recurse: yes
          
    - name: apache2
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^DocumentRoot /var/www/html" line="DocumentRoot /applications/vendo-iac-test" state=present
      notify:
        - restart apache2    
    - name: example copying file with owner and permissions
      copy:
      src: ./index.php
      dest: /applications/vendo-iac-test/index.php
      owner: www-data
      group: 222-data
      mode: 0755    
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted